name: Build C GUI App

on:
  push:

jobs:
  build:
    name: Compile GTK App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install GTK dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev build-essential

      - name: Compile C GUI
        run: gcc src/main.c -o myguiapp `pkg-config --cflags --libs gtk+-3.0`

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: gtk-linux-executable
          path: myguiapp
