name: Build

on: workflow_dispatch

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - run: |
           git clone https://github.com/hermit-os/kernel.git
           cd kernel
           cargo xtask build --arch x86_64
